version: '2'
services:
  #Build a Postgres Dockfile
  dac-phonebook-core-db:
    build: ./dac-phonebook-core/src/main/resources/banco
    image: dac-phonebook-core-db:latest
    ports:
      - "5433:5432"
    container_name: dac-phonebook-core-db
  #Build a Core Dockfile
  dac-phonebook-core:
    build: ./dac-phonebook-core
    image: dac-phonebook-core:latest
    links:
      - "dac-phonebook-core-db:dac-phonebook-core-db"
    ports:
      - "8081:8080"
      - "1098:1099"
      - "1097:1098"
      - "3874:3873"
      - "3701:3700"
      - "8182:8181"
      - "8010:8009"
    container_name: dac-phonebook-core
  #Build a Web Dockfile
  dac-phonebook-web:
    build: ./dac-phonebook-web
    image: dac-phonebook-web:latest
    links:
      - "dac-phonebook-core:dac-phonebook-core"
    ports:
      - "8082:8080"
    container_name: dac-phonebook-web
