FROM postgres
MAINTAINER Wensttay <yattsnew@gmail.com>
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD 12345
ENV POSTGRES_DB dac-phonebook
COPY create.sql /docker-entrypoint-initdb.d/
COPY data.sql /docker-entrypoint-initdb.d/